# fly.toml app configuration file generated for vaadin-gh-community-bot on 2023-11-10T15:26:05-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vaadin-gh-community-bot"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
